Locales['en'] = {
    -- Radar interface (NUI)
    radar_title         = 'AIR RADAR',
    contacts_detected   = 'DETECTED CONTACTS',
    no_contacts         = 'NO CONTACTS',
    close               = 'Close Radar',
    info_radius         = 'RANGE',
    info_min_alt        = 'MIN ALT',
    info_contacts       = 'CONTACTS',
    info_status         = 'STATUS',
    info_hidden         = 'HIDDEN',
    status_active       = 'ACTIVE',
    info_zoom           = 'ZOOM',
    zoom_in             = 'ZOOM IN',
    zoom_out            = 'ZOOM OUT',
    zoom_reset          = 'RESET',
    type_plane          = 'PLANE',
    type_heli           = 'HELI',
    label_type          = 'TYPE',
    label_model         = 'MODEL',
    label_alt           = 'ALT',
    label_speed         = 'SPD',
    label_heading       = 'HDG',
    label_distance      = 'DIST',
    label_bearing       = 'BRG',
    label_plate         = 'PLATE',
    unknown             = 'UNKNOWN',
    unknown_aircraft    = 'UNKNOWN',
    btn_hide            = 'HIDE',
    btn_show            = 'SHOW',

    -- Cardinal directions
    cardinal_n          = 'N',
    cardinal_s          = 'S',
    cardinal_e          = 'E',
    cardinal_w          = 'W',
    cardinal_ne         = 'NE',
    cardinal_nw         = 'NW',
    cardinal_se         = 'SE',
    cardinal_sw         = 'SW',

    -- Notifications
    notify_radar_activated      = 'Radar %s activated.',
    notify_access_denied        = 'Access denied.',
    notify_radar_not_found      = 'Radar not found or disabled.',
    notify_player_error         = 'Error verifying player.',
    notify_wrong_job            = 'You don\'t have the required job to operate this radar.',
    notify_wrong_grade          = 'Your rank is insufficient to operate this radar.',
    notify_no_permission        = 'You don\'t have admin permissions to use this command.',
    notify_transponder_on       = 'Transponder ON — your aircraft is visible on radar.',
    notify_transponder_off      = 'Transponder OFF — your aircraft appears as unknown.',
    notify_not_in_aircraft      = 'You must be piloting an aircraft to use the transponder.',
    notify_transponder_usage    = 'Usage: /transponder [on/off]',
    notify_interact             = '~INPUT_CONTEXT~ Access Radar',

    -- Framework errors
    error_no_framework          = 'No compatible framework detected (QBCore/ESX). The yc-radar resource will not start.',
    error_framework_not_found   = 'Configured framework \'%s\' was not detected. Make sure the resource is started or change Config.Framework to \'auto\'.',
}
